export const categories = [
  {
    parent: "Women",
    child: [
      `Clothing`,
      `Traditional Clothing`,
      `Women's Bags`,
      `Shoes`,
      `Accessories`,
      `Lingerie, Sleep & Lounge`,
      `Girl's Fashion `,
    ],
  },
  {
    parent: "Electonic Devices",
    child: [
      `Smartphones`,
      `Tablets`,
      `Laptops`,
      `Desktops`,
      `Monitors`,
      `Gaming Consoles`,
      `Cameras`,
    ],
  },
  {
    parent: "Watches, Bags, Jewellery",
    child: [
      `Men's Watches`,
      `Women's Watches`,
      `Kid's Watches`,
      `Sunglasses`,
      `Eyeglasses`,
      `Women Fashion Jewellery`,
      `Men Fashion Jewellery `,
    ],
  },
  {
    parent: "Electronic Accessories",
    child: [
      `Mobile Accessories`,
      `Audio`,
      `Wearable`,
      `Console Accessories`,
      `Camera Accessories`,
      `Computer Accessories`,
      `Storage`,
      `Computer Components`,
      `Network Components`,
    ],
  },
  {
    parent: "Health & Beauty",
    child: [
      `Bath & Body`,
      `Beauty Tools`,
      `Fragrances`,
      `Hair Care`,
      `Makeup`,
      `Men's Care`,
      `Personal Care`,
      `Skin Care`,
    ],
  },
  {
    parent: "Groceries & Pets",
    child: [
      `Groceries`,
      `Beverages`,
      `Breakfast, Choco & Snacks`,
      `Food Staples`,
      `Cooking Ingredients`,
      `Laundry & Household`,
      `Wines, Beers & Spirits`,
      `Pet Supplies `,
    ],
  },
  {
    parent: "Sports & Outdoors",
    child: [
      `Men Shoes & Clothing`,
      `Women Shoes & Clothing`,
      `Outdoor Recreation`,
      `Exercise & Fitness`,
      `Water Sports`,
      `Racket Sports`,
      `Team Sports`,
      `Water Bottles`,
      `Travel & Luggage`,
      `Sports Nutrition`,
    ],
  },
  {
    parent: "Home & Lifestyle",
    child: [
      `Bath`,
      `Bedding`,
      `Furniture`,
      `Kitchen & Dining`,
      `Lighting`,
      `Laundry & Cleaning`,
      `Stationery & Craft`,
      `Musical Instruments`,
      `Digital Goods `,
    ],
  },
];
